import type { Pipeline, PipelineIndexEntry } from "@/types/pipeline";
import { ApiError, get } from "./client";

/**
 * Production endpoint shapes (proposed):
 *   GET /api/v1/pipelines              → PipelineIndexEntry[]
 *   GET /api/v1/pipelines/:ddq_id      → Pipeline
 *
 * Today both forms read from `apps/ui/src/mocks/fixtures/pipelines/`, which is
 * generated by `data/bootstrap/13_build_pipeline_fixtures.py` from the real
 * sealed-run manifests under `data/manifests/runs/`. Shape on the wire matches
 * the fixtures verbatim — no transformation is needed when the backend lands.
 */
export async function listPipelines(): Promise<PipelineIndexEntry[]> {
  return get<PipelineIndexEntry[]>(
    `/api/v1/pipelines`,
    () =>
      import("@/mocks/fixtures/pipelines-index.json").then((m) => ({
        default: m.default as unknown as PipelineIndexEntry[],
      })),
  );
}

const pipelineModules = import.meta.glob<{ default: Pipeline }>(
  "@/mocks/fixtures/pipelines/*.json",
);

export async function getPipeline(ddqId: string): Promise<Pipeline> {
  // Fixture is only authoritative in fixture mode; in http mode the API
  // serves freshly-sealed packets that don't have a static fixture yet.
  const entry = Object.entries(pipelineModules).find(([path]) =>
    path.endsWith(`/${ddqId}.json`),
  );
  const fixtureLoader = entry
    ? () => entry[1]().then((m) => ({ default: m.default as unknown as Pipeline }))
    : () =>
        Promise.reject(
          new ApiError("Pipeline not found", 404, `/api/v1/pipelines/${ddqId}`),
        );
  return get<Pipeline>(`/api/v1/pipelines/${ddqId}`, fixtureLoader);
}
